<template>
<div >
<!-- <xml version="1.0" encoding="UTF-8"> -->
<!-- 2019-11-18 10:55:58 Generated by QCAD 3.23.0 SVG Exporter -->
<svg>
{{svgpath}}
</svg>
</div>
</template>

<script>
export default {
  props: {

     svgpath: {
      type: String,
      default: false
     }
    },



  data: function() {
    return {};
  },
  created: function() {},

  watch: { },
  computed: {},
methods: {},

  filters: {},
 mounted() {
    console.log("Component mounted.");
  },

};
</script>
